builders:
  jsonBuilder:
    import: "package:json_dart/json_dart.dart"
    builder_factories: ["jsonBuilder"]
    build_extensions: {"^jsons/{{}}.json": ["lib/models/{{}}.g.dart"]}
    auto_apply: root_package 
    build_to: source 


targets:
  $default:
    sources:
      - jsons/**
      - lib/models/**
      - $package$
      - lib/$lib$

   