name: json_dart
description: "A json to dart model generator."
version: 0.0.1
homepage: "https://github.com/scnon/json_dart"

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  build: ^2.4.1 
  build_config: ^1.1.1 

  glob: ^2.1.2
  dart_style: ^2.3.6

dev_dependencies:
  build_runner: any 